name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_cc:
    name: Check Coding Conventions
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Check code formatting
        run: find src/ include/ -regex ".*\.\(hpp\|cpp\|c\|h\)$" -execdir clang-format --style=LLVM --dry-run --Werror {} + ;

  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    needs: check_cc
    
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Linux GCC 14,        os: ubuntu-24.04, profile: ubuntu-24.04 }
        - { name: Windows MSVC 19.4,   os: windows-2022, profile: windows-2022 }
        - { name: MacOS ARM Clang 18,  os: macos-15,     profile: macos-15 }

    steps:
    - uses: actions/checkout@v2

    - name: Install pip dependencies
      run: pip install -r requirements.txt
    
    - name: Install conan dependencies && configure
      run: |
        conan install . --build=missing --profile:all ${{github.workspace}}/.github/profiles/${{matrix.platform.profile}} -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

    - name: Build
      run: conan build . --profile:all ${{github.workspace}}/.github/profiles/${{matrix.platform.profile}}
